import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import {
  ArrowLeft,
  Camera,
  Calendar,
  Clock,
  Copy,
  DollarSign,
  Edit,
  LogOut,
  Map,
  MessageCircle,
  Trash2,
  Users,
  Sparkles,
  MapPin,
} from "lucide-react";
import { format } from "date-fns";

import { useTripStore } from "../store/tripStore";
import { useAuthStore } from "../store/authStore";
import { useSocket } from "../hooks/useSocket";
import { tripService } from "../services/tripService";

import AIItineraryBoard from "../components/ai/AIItineraryBoard";
import WeatherCard from "../components/ai/WeatherCard";
import RouteCard from "../components/ai/RouteCard";
import BudgetBreakdown from "../components/ai/BudgetBreakdown";
import ItineraryBoard from "../components/ItineraryBoard";
import ExpenseWidget from "../components/ExpenseWidget";
import PhotoGallery from "../components/PhotoGallery";
import ChatBox from "../components/ChatBox";

const TABS = [
  { id: "overview", label: "Overview", icon: Sparkles },
  { id: "itinerary", label: "Itinerary", icon: Map },
  { id: "expenses", label: "Expenses", icon: DollarSign },
  { id: "photos", label: "Photos", icon: Camera },
  { id: "chat", label: "Chat", icon: MessageCircle },
  { id: "members", label: "Members", icon: Users },
];

export default function TripDetails() {
  const { id } = useParams();
  const navigate = useNavigate();

  const {
    currentTrip,
    itinerary,
    fetchTrip,
    setItinerary,
    loading,
    updateTrip,
    deleteTrip,
    leaveTrip,
  } = useTripStore();
  const { user } = useAuthStore();

  const [copied, setCopied] = useState(false);
  const [editing, setEditing] = useState(false);
  const [activeTab, setActiveTab] = useState("overview");
  const [showManualEditor, setShowManualEditor] = useState(false);
  const [title, setTitle] = useState("");
  const [destination, setDestination] = useState("");
  const itinerarySectionRef = useRef(null);

  useSocket(id);

  useEffect(() => {
    if (!id) return;
    fetchTrip(id);
  }, [id, fetchTrip]);

  useEffect(() => {
    const fetchItinerary = async () => {
      if (!id) return;
      try {
        const data = await tripService.getItinerary(id);
        setItinerary(data.itinerary);
      } catch {}
    };

    fetchItinerary();
  }, [id, setItinerary]);

  useEffect(() => {
    if (!currentTrip) return;
    setTitle(currentTrip.title || "");
    setDestination(currentTrip.destination || "");
  }, [currentTrip]);

  const isAdmin =
    currentTrip?.admin?._id === user?.id || currentTrip?.admin === user?.id;

  const duration = Math.max(
    1,
    Math.ceil(
      (new Date(currentTrip?.endDate) - new Date(currentTrip?.startDate)) /
        (1000 * 60 * 60 * 24),
    ),
  );

  const aiItineraryData = useMemo(() => {
    if (!itinerary?.days?.length) {
      return {
        available: false,
        days: [],
        local_cuisine: [],
        packing_tips: [],
      };
    }

    return {
      available: true,
      days: itinerary.days.map((day) => ({
        day: day.day,
        date: day.date,
        title: day.title,
        day_summary: day.summary,
        activities: (day.activities || []).map((activity) => ({
          ...activity,
          category: activity.category || "other",
          cost: activity.cost || 0,
        })),
      })),
      local_cuisine: itinerary.aiInsights?.localCuisine || [],
      packing_tips: itinerary.aiInsights?.packingTips || [],
      highlights: itinerary.aiInsights?.travelTips || [],
    };
  }, [itinerary]);

  const weatherData = useMemo(() => {
    if (!itinerary?.aiData?.weather) return { available: false };

    const forecast = (itinerary.aiData.weather.forecast || []).map(
      (item, index) => ({
        day: index + 1,
        condition: item.condition || "Cloudy",
        humidity: item.humidity ?? 0,
        temperature: {
          min: item.temperature ?? 0,
          max: item.temperature ?? 0,
        },
      }),
    );

    return {
      available: !!itinerary.aiData.weather.available,
      destination: itinerary.meta?.destination || currentTrip?.destination,
      summary:
        itinerary.aiInsights?.safetyNotes?.[0] || "Forecast generated by AI",
      forecast,
    };
  }, [currentTrip?.destination, itinerary]);

  const routeData = useMemo(() => {
    if (!itinerary?.aiData?.route) return { available: false };

    return {
      available: !!itinerary.aiData.route.available,
      origin: itinerary.meta?.origin || "Origin",
      destination:
        itinerary.meta?.destination ||
        currentTrip?.destination ||
        "Destination",
      distance: itinerary.aiData.route.distance || "-",
      duration: itinerary.aiData.route.duration || "-",
      mode: itinerary.aiData.route.recommendedMode || "Travel",
      alternatives: [],
    };
  }, [currentTrip?.destination, itinerary]);

  const budgetData = useMemo(() => {
    if (!itinerary?.aiData?.budget) return { available: false };

    const total = itinerary.aiData.budget.total || 0;
    const people = itinerary.meta?.people || 1;
    const days = itinerary.meta?.days || duration;

    return {
      available: total > 0,
      currency:
        itinerary.aiData.budget.currency || itinerary.meta?.currency || "INR",
      tier: "medium",
      people,
      days,
      tips: itinerary.aiInsights?.travelTips || [],
      breakdown: {
        transport: itinerary.aiData.budget.transport || 0,
        hotel: itinerary.aiData.budget.hotel || 0,
        food: itinerary.aiData.budget.food || 0,
        activities: itinerary.aiData.budget.activities || 0,
        total,
        per_person: people > 0 ? Math.round(total / people) : total,
        per_day: days > 0 ? Math.round(total / days) : total,
      },
    };
  }, [duration, itinerary]);

  const handleCopyInvite = async () => {
    if (!currentTrip?.inviteCode) return;

    try {
      await navigator.clipboard.writeText(currentTrip.inviteCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      alert("Failed to copy invite code");
    }
  };

  const handleSaveTripMeta = async () => {
    if (!title.trim() || !destination.trim()) {
      alert("Title and destination cannot be empty");
      return;
    }

    try {
      await updateTrip(id, {
        title: title.trim(),
        destination: destination.trim(),
      });
      setEditing(false);
      await fetchTrip(id);
    } catch (err) {
      alert(err.response?.data?.message || "Failed to update trip");
    }
  };

  const handleDelete = async () => {
    if (!window.confirm("Delete this trip permanently?")) return;

    try {
      await deleteTrip(id);
      navigate("/dashboard");
    } catch (err) {
      alert(err.response?.data?.message || "Failed to delete trip");
    }
  };

  const handleLeave = async () => {
    if (!window.confirm("Leave this trip?")) return;

    try {
      await leaveTrip(id);
      navigate("/dashboard");
    } catch (err) {
      alert(err.response?.data?.message || "Failed to leave trip");
    }
  };

  const handleManualItinerarySaved = () => {
    setShowManualEditor(false);
    setActiveTab("itinerary");
    itinerarySectionRef.current?.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });
  };

  if (loading && !currentTrip) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-10 h-10 border-4 border-primary-500 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!currentTrip) return null;

  return (
    <div className="min-h-screen bg-[var(--bg)]">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-6 space-y-6">
        <button
          onClick={() => navigate("/dashboard")}
          className="btn-ghost text-sm inline-flex items-center gap-2"
        >
          <ArrowLeft size={15} /> Dashboard
        </button>

        <TripHeader
          trip={currentTrip}
          itinerary={itinerary}
          duration={duration}
          copied={copied}
          isAdmin={isAdmin}
          onCopyInvite={handleCopyInvite}
          onEdit={() => setEditing(true)}
          onOpenDetails={() => setActiveTab("overview")}
        />

        <div className="border-b border-gray-200 dark:border-surface-850">
          <div className="flex gap-2 overflow-x-auto pb-2">
            {TABS.map(({ id: tabId, label, icon: Icon }) => (
              <button
                key={tabId}
                onClick={() => setActiveTab(tabId)}
                className={
                  activeTab === tabId ? "tab-btn-active" : "tab-btn-inactive"
                }
              >
                <Icon size={15} />
                {label}
              </button>
            ))}
          </div>
        </div>

        {activeTab === "overview" && (
          <section className="space-y-3" id="trip-details">
            <h2 className="section-title">AI Overview</h2>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              <WeatherCard weather={weatherData} />
              <RouteCard route={routeData} />
              <BudgetBreakdown budget={budgetData} />
              <AIInsightsPanel aiInsights={itinerary?.aiInsights} />
            </div>
          </section>
        )}

        {activeTab === "itinerary" && (
          <section className="space-y-4" ref={itinerarySectionRef}>
            <h2 className="section-title">Itinerary</h2>
            <AIItineraryBoard itinerary={aiItineraryData} />
            <div className="card p-4">
              <div className="flex items-center justify-between gap-3 mb-3">
                <p className="text-sm font-semibold text-gray-800 dark:text-gray-200">
                  Manual Itinerary
                </p>
                <button
                  className="btn-primary text-xs"
                  onClick={() => setShowManualEditor((prev) => !prev)}
                >
                  {showManualEditor ? "Close Editor" : "Edit Itinerary"}
                </button>
              </div>

              {showManualEditor ? (
                <ItineraryBoard
                  tripId={id}
                  isEditMode
                  onManualSave={handleManualItinerarySaved}
                  onCancelEdit={() => setShowManualEditor(false)}
                />
              ) : (
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  Click "Edit Itinerary" to open manual edit mode.
                </p>
              )}
            </div>
          </section>
        )}

        {activeTab === "expenses" && (
          <section>
            <ExpenseWidget tripId={id} trip={currentTrip} />
          </section>
        )}

        {activeTab === "photos" && (
          <section>
            <PhotoGallery tripId={id} trip={currentTrip} />
          </section>
        )}

        {activeTab === "chat" && (
          <section>
            <ChatBox tripId={id} />
          </section>
        )}

        {activeTab === "members" && (
          <MembersSection
            trip={currentTrip}
            userId={user?.id}
            isAdmin={isAdmin}
            onCopyInvite={handleCopyInvite}
          />
        )}

        <div className="flex gap-2 justify-end">
          {isAdmin ? (
            <button
              onClick={handleDelete}
              className="btn-secondary text-sm text-red-500"
            >
              <Trash2 size={14} /> Delete Trip
            </button>
          ) : (
            <button
              onClick={handleLeave}
              className="btn-secondary text-sm text-red-500"
            >
              <LogOut size={14} /> Leave Trip
            </button>
          )}
        </div>
      </div>

      {editing && (
        <div className="fixed inset-0 z-40 bg-black/40 flex items-center justify-center p-4">
          <div className="card w-full max-w-md p-5">
            <h3 className="font-bold text-lg mb-4">Edit Trip</h3>
            <div className="space-y-3">
              <div>
                <label className="label-text">Title</label>
                <input
                  className="input-field"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                />
              </div>
              <div>
                <label className="label-text">Destination</label>
                <input
                  className="input-field"
                  value={destination}
                  onChange={(e) => setDestination(e.target.value)}
                />
              </div>
            </div>
            <div className="flex justify-end gap-2 mt-5">
              <button
                className="btn-secondary text-sm"
                onClick={() => setEditing(false)}
              >
                Cancel
              </button>
              <button
                className="btn-primary text-sm"
                onClick={handleSaveTripMeta}
              >
                Save
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function TripHeader({
  trip,
  itinerary,
  duration,
  copied,
  isAdmin,
  onCopyInvite,
  onEdit,
  onOpenDetails,
}) {
  const destination = itinerary?.meta?.destination || trip.destination;
  const origin = itinerary?.meta?.origin || "Origin";
  const people = itinerary?.meta?.people || trip.members?.length || 1;
  const vibe = itinerary?.meta?.vibe || "balanced";
  const budget =
    itinerary?.aiData?.budget?.total ||
    itinerary?.meta?.budget ||
    trip.budget ||
    0;
  const currency =
    itinerary?.aiData?.budget?.currency ||
    itinerary?.meta?.currency ||
    trip.currency ||
    "INR";

  return (
    <header className="card overflow-hidden">
      <div className="p-6 bg-gradient-to-r from-primary-500/10 via-cyan-500/10 to-emerald-500/10 border-b border-gray-100 dark:border-surface-850">
        <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <h1 className="text-2xl sm:text-3xl font-extrabold text-gray-900 dark:text-white">
                {destination}
              </h1>
              <span className="badge bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 text-xs">
                AI Plan
              </span>
            </div>
            <p className="text-sm text-gray-500 dark:text-gray-400 flex items-center gap-1.5">
              <MapPin size={13} /> {origin} to {destination}
            </p>
          </div>

          <div className="flex flex-wrap gap-2">
            {isAdmin && (
              <button onClick={onCopyInvite} className="btn-primary text-sm">
                <Copy size={14} /> {copied ? "Copied" : "Invite Member"}
              </button>
            )}
          </div>
        </div>
      </div>

      <div className="p-5 grid grid-cols-2 md:grid-cols-5 gap-3">
        <InfoPill
          icon={<Calendar size={13} />}
          label="Dates"
          value={`${format(new Date(trip.startDate), "MMM d")} - ${format(new Date(trip.endDate), "MMM d, yyyy")}`}
        />
        <InfoPill
          icon={<Clock size={13} />}
          label="Days"
          value={`${duration} days`}
        />
        <InfoPill
          icon={<Users size={13} />}
          label="People"
          value={`${people} travelers`}
        />
        <InfoPill
          label="Budget"
          value={`${currency} ${Number(budget).toLocaleString("en-IN")}`}
        />
        <InfoPill label="Vibe" value={vibe} />
      </div>
    </header>
  );
}

function InfoPill({ icon, label, value }) {
  return (
    <div className="bg-gray-50 dark:bg-surface-850 rounded-xl p-3">
      <p className="text-[10px] uppercase tracking-wide text-gray-400 dark:text-gray-500 mb-1 flex items-center gap-1">
        {icon}
        {label}
      </p>
      <p className="text-sm font-semibold text-gray-800 dark:text-gray-200">
        {value}
      </p>
    </div>
  );
}

function MembersSection({ trip, userId, isAdmin, onCopyInvite }) {
  const [inviteEmail, setInviteEmail] = useState("");
  const [inviteStatus, setInviteStatus] = useState(null); // null | "sending" | "sent" | "error"
  const [inviteError, setInviteError] = useState("");

  const handleSendInvite = async () => {
    if (!inviteEmail.trim()) return;
    setInviteStatus("sending");
    setInviteError("");
    try {
      await tripService.sendInviteEmail(trip._id, inviteEmail.trim());
      setInviteStatus("sent");
      setInviteEmail("");
      setTimeout(() => setInviteStatus(null), 3000);
    } catch (err) {
      setInviteError(err.response?.data?.message || "Failed to send invite");
      setInviteStatus("error");
    }
  };

  return (
    <section className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="section-title">Members ({trip.members?.length || 0})</h2>
        {isAdmin && (
          <button onClick={onCopyInvite} className="btn-secondary text-sm">
            <Copy size={14} /> Copy Invite Code
          </button>
        )}
      </div>

      {/* Invite by email — admin only */}
      {isAdmin && (
        <div className="card p-4 space-y-2">
          <p className="text-sm font-semibold text-gray-800 dark:text-gray-200">
            Invite via Email
          </p>
          <div className="flex gap-2">
            <input
              type="email"
              className="input-field flex-1"
              placeholder="friend@example.com"
              value={inviteEmail}
              onChange={(e) => {
                setInviteEmail(e.target.value);
                setInviteStatus(null);
                setInviteError("");
              }}
              onKeyDown={(e) => e.key === "Enter" && handleSendInvite()}
            />
            <button
              className="btn-primary text-sm whitespace-nowrap"
              onClick={handleSendInvite}
              disabled={inviteStatus === "sending" || !inviteEmail.trim()}
            >
              {inviteStatus === "sending" ? "Sending..." : "Send Invite"}
            </button>
          </div>
          {inviteStatus === "sent" && (
            <p className="text-xs text-emerald-600 dark:text-emerald-400">
              ✓ Invite sent successfully!
            </p>
          )}
          {inviteStatus === "error" && (
            <p className="text-xs text-red-500">{inviteError}</p>
          )}
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {trip.members?.map((member) => (
          <div
            key={member.user?._id || member.user}
            className="card p-4 flex items-center justify-between"
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary-500 to-cyan-500 text-white font-bold flex items-center justify-center">
                {member.user?.name?.[0]?.toUpperCase() || "U"}
              </div>
              <div>
                <p className="font-semibold text-sm text-gray-800 dark:text-gray-100">
                  {member.user?.name || "Member"}
                  {(member.user?._id || member.user) === userId ? " (you)" : ""}
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  {member.user?.email || "-"}
                </p>
              </div>
            </div>
            <span
              className={`badge text-xs ${
                member.role === "admin"
                  ? "bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400"
                  : "bg-gray-100 dark:bg-surface-800 text-gray-600 dark:text-gray-400"
              }`}
            >
              {member.role}
            </span>
          </div>
        ))}
      </div>
    </section>
  );
}

function AIInsightsPanel({ aiInsights }) {
  const sections = [
    { title: "Local Cuisine", items: aiInsights?.localCuisine || [] },
    { title: "Travel Tips", items: aiInsights?.travelTips || [] },
    { title: "Packing Tips", items: aiInsights?.packingTips || [] },
    { title: "Safety Notes", items: aiInsights?.safetyNotes || [] },
  ];

  return (
    <div className="card p-5">
      <h3 className="font-bold text-gray-900 dark:text-gray-100 text-sm mb-4">
        AI Insights
      </h3>
      <div className="space-y-3">
        {sections.map((section) => (
          <div key={section.title}>
            <p className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-1">
              {section.title}
            </p>
            {section.items.length ? (
              <ul className="space-y-1">
                {section.items.slice(0, 4).map((item, index) => (
                  <li
                    key={`${section.title}-${index}`}
                    className="text-xs text-gray-600 dark:text-gray-300"
                  >
                    - {item}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-xs text-gray-400 dark:text-gray-500 italic">
                No data available
              </p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
